### ISSUE TITLE
[Issue]: Request for Implement for actual hardware

### ISSUE THREAD

**Issue by hocken-li** [Xilinx/xup_aie_training#25]
### Is there an existing issue related to your problem?

- [X] I have searched the existing issues

### Lab

Vector Add 2

### Section

```markdown
Vector Add lab, part 2
```

### Step

```markdown
Add kernel linking file
Configure x86 compilation
```

### Description

```markdown
1. After [Add kernel linking file], what can I do next? Build the file in the aie_vadd_system_hw_link.prj? 

I have met a problem, I couldn't click [Export hardware(XSA)]. It there another way to build XSA? Maybe use the makefile, but it's there anyway to write the make file? It is very hard to learn how to write makefile, because there is aie and hls in the project. 

I haven't seen any tutorials on makefiles so far. Could you please give me some guidance?

2. After Configure x86 compilation, what should we do next? This is a build method that uses a graphical interface, In the website, [Implement for actual hardware] only write COMING SOON... 
How to build the xclbin file?  Is there any tutorials to tell us how to write makefile to build the target?
In my current understanding, because of the aie graph, the v++ package command need to add some aie setting, I don't know if it's true, looking forward to you reply. 
I would really appreciate it!
```

### Instance

```markdown
my host server vck5000
```

### Vitis

```markdown
2022.2
```

### XRT

```markdown
2.14.384
```

### Platform

```markdown
xilinx_vck5000_gen4*8_qdma_2_202220_1
```

### Linux distribution

```markdown
ubuntu 20.04.6 LTS
```

**Comment by mariodruiz** [comment]
Hi @hocken-li,

You can run `make` in the directory `sources/vadd_lab`, this should generate the xclbin and the host code

**Comment by hocken-li** [comment]
> Hi @hocken-li,
> 
> You can run `make` in the directory `sources/vadd_lab`, this should generate the xclbin and the host code

Hi @mariodruiz 
Thank you very much! I used the `make all` to generate the xclbin and the host code. But when I run `./vadd.exe ../build.hw/vadd.xclbin`, there is some problem: 

`Open the device 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unexected error creating shim library name
Aborted (core dumped)`

It seems to be the problem of `auto device = xrt::device(2);`. (My vck5000 device No. is 2) could help me to solve the problem? I would really appreciate it!

**Comment by mariodruiz** [comment]
Hi @hocken-li,

Can you try to open use the PCIe BDF instead?

https://xilinx.github.io/XRT/master/html/xrt_native_apis.html#device-and-xclbin

**Comment by hocken-li** [comment]
> > Hi @hocken-li,
> > You can run `make` in the directory `sources/vadd_lab`, this should generate the xclbin and the host code
> 
> Hi @mariodruiz Thank you very much! I used the `make all` to generate the xclbin and the host code. But when I run `./vadd.exe ../build.hw/vadd.xclbin`, there is some problem:
> 
> `Open the device terminate called after throwing an instance of 'std::runtime_error' what(): Unexected error creating shim library name Aborted (core dumped)`
> 
> It seems to be the problem of `auto device = xrt::device(2);`. (My vck5000 device No. is 2) could help me to solve the problem? I would really appreciate it!

It is the problem of may server, I can run and PASS the test. I'm very sorry to disturb you!
Best wish.

**Comment by mariodruiz** [comment]
Please close the issue if it is resolved
